version: "3.9"

services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    hostname: samba
    restart: unless-stopped
    ports:
      - 139:139/tcp
      - 445:445/tcp
    volumes_from:
      - jellyfin:/media:ro
    environment:
      TZ: 'Europe/Copenhagen'
      SHARE: "media;/media;yes;no;no;maroka;maroka;;A Share for Media"
      USER: "maroka;Rgy24sqf"